### ISSUE TITLE
2 potential improvements

### ISSUE THREAD

**Issue by thyco** [flakysalt/Blish-HUD-CharacterKeybinds#7]
Hello,

I started using your module and it's working great. I do have 2 improvements:

1. Store the last applied keybinds after applying a keybind. When switching to another character or spec and the new character or spec would have the same keybinds applied, skip apply.
2. Is there a way to set a default keybinds name. Like character1 => keybinds1, character2 => keybinds2, all other characters keybinds3.

Thanks for the great work already.

**Comment by flakysalt** [comment]
Hey there, thanks for the input.
Keeping track of what key binds are currently in use sounds reasonable. I'll look into that.

I need help understanding the second point. Do you want a default name so you are not forced to change it whenever you create a new set of key binds?

**Comment by thyco** [comment]
I'll try to explain the second point differently.

Let's say we have 2 stored keybinds : default and necro.
There are 4 characters on the account : a necro, a warrior, a ranger and a mesmer.

It would be nice to able to say:
- Necro character use keybinds "necro".
- All other characters use keybinds "default".

If I understand it correctly, at this moment I need to put the following config:
- Necro character use keybinds "necro".
- Warrior character use keybinds "default".
- Ranger character use keybinds "default".
- Mesmer character use keybinds "default".

I hope this is a better explanation.

**Comment by thyco** [comment]
You’re welcome. Thanks for looking into it. 👍

**Comment by flakysalt** [comment]
Hey there, quick update on this. Added both of your suggestions to the module and will be available in version 1.1 later this week.
Thanks for the great suggestion!

**Comment by thyco** [comment]
Sweet. Looking forward to checking it out. Thanks for implementing them.
